### PR TITLE
updating the DC St. Louis 2017-06-17 website

### PR DESCRIPTION
**Pull request by canghel**
Hi there,

It is my first time setting up a website for DC carpentry and I went to my data science office hours to get help.  I have forked and edited the site last week and Bo and I chatted today and the major lesson structure will stay the same, although we may still have a few edits.   I hope I am doing this okay?

Thank you!
Catalina

### CODE REVIEW

**Comment by tracykteal** [comment]
This looks good! I'll merge your PR.

**Comment by tracykteal** [comment]
Web site appears at http://www.datacarpentry.org/2017-06-17-stlouis/

**Comment by tracykteal** [comment]
You won't be able to get through all of that content in one day though. Would you want to set up a meeting for this week or next to talk about the schedule?

**Comment by canghel** [comment]
Hi Tracy,

Yes, thank you!   It is my first time teaching as a lead instructor, so any
advice would help a lot!!

Would sometime next week be okay?  I am not supposed to do any teaching
while at work, but I have a flexible schedule for lunch, so either late
morning or early afternoon would work (or anytime after work too)!

Also, I was asked by one student what the workshop ID is for the
before-workshop survey question.  Would it be just "2017-06-17-stlouis"?

Thank you!

All the best,
Catalina

**Pull request merged**
